### ISSUE TITLE
Publish releases on slack

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#144]
As an (potential) user,
I want to see new CoMPAS repository releases via the maillinglist (CoMPAS@lists.lfenergy.org)
So can keep track of the development and consider upgrade/use options

Background:
We can release per repository or per deployment. The easy way for now is to just release the separate repositories.
To find out: how to send the e-mails.

**Comment by dlabordus** [comment]
Sending a email from GitHub is hard to do, because you need something like SendGrid or create a GMail Account for it.

So we decided to switch to Slack, because a integration with slack is already in place.
The "compas" channel has been updated to receive a message when a new release is created in GitHub.
