### ISSUE TITLE
Automate checking Sign-off flag

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#6]
As a developer
I want to describe how to automate checking for the sign-off flags in commits (locally or remote)
So I don't have to check this manually

Acceptance criteria:
- Document how to do this in the Contributing repo.

**Comment by Sander3003** [comment]
@Flurb is this still relevant?

**Comment by Flurb** [comment]
@Sander3003 yes, but it's more a nice-to-have feature.

**Comment by dlabordus** [comment]
Is it allowed to sign off with a GPG Key? 

Because then it's possible to auto sign off.
See tip at https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
And https://community.element14.com/technologies/security/b/blog/posts/git-sign-your-commits-with-a-certificate how to configure and add a GPG Key.

**Comment by Sander3003** [comment]
Sounds as a good solution. We could try this.

**Comment by dlabordus** [comment]
GPG Key is not a alternative for the purpose done in LF Energy, so developers need to add the -s (--sign-off) to every commit.
